server:
  port: ${PORT:${SERVER_PORT:0}}
 
eureka:
  instance:
    hostname: localhost
    instance_id: ${eureka.instance.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      default-zone: http://localhost:8761/
 
